### PR TITLE
Bug fixes, numerous enhancements

### PR DESCRIPTION
**Pull request by ErichZimmer**
**Warning:**
There was a bug with OpenPIV local median validation filter when running the postprocessing algorithm in the GUI (says something like `filter footprint array has incorrect shape`). To validate that this bug is truly a bug, please run the branch with the enhancements to see if it occurs on your computer. 

Notable enhancements:

- Redistributed widgets to support smaller screen sizes
- Fixed noticeable bugs with newer OpenPIV versions
- Fixed Gaussian high pass filter (now a true high pass filter)
- new colorbars
- fixed contours (now has origin top left)
- progressbar
- percent invalid vectors
- first pass and second pass on have customizable validation/postprocessing
- use all parameters of new windef version
- control line density of profile plots

Future enhancements:

- individual image processing
- individual result processing
- image object masking 
- GUI based, interactable (Similar to PIVlab, but with advanced features)
- rectangular windowing with repeated correlation (will be discussed on OpenPIV enhancements)
- ensemble average

### CODE REVIEW

**Review by eguvep — APPROVED** [review]
Good work – thanks again!

**Comment by alexlib** [comment]
@ErichZimmer @eguvep please check - on my Linux Mint machine with conda `Python 3.8.5 (default, Sep  4 2020, 07:30:14)`

`pip install openpiv --upgrade --force-reinstall` 
`pip install -e .`

from the cloned repository leads to the error when I run:

`python -m openpivgui.OpenPivGui`

```
(openpivtkgui) user@Turbo-NUC7:~/Downloads/repos/openpiv_tk_gui$ python -m openpivgui.OpenPivGui
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/openpivtkgui/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/user/miniconda3/envs/openpivtkgui/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/user/Downloads/repos/openpiv_tk_gui/openpivgui/OpenPivGui.py", line 1195, in <module>
    openPivGui = OpenPivGui()
  File "/home/user/Downloads/repos/openpiv_tk_gui/openpivgui/OpenPivGui.py", line 113, in __init__
    self.__init_widgets()
  File "/home/user/Downloads/repos/openpiv_tk_gui/openpivgui/OpenPivGui.py", line 317, in __init_widgets
    self.__init_vec_colorpicker(key)
  File "/home/user/Downloads/repos/openpiv_tk_gui/openpivgui/OpenPivGui.py", line 947, in __init_vec_colorpicker
    self.valid_color = tk.Button(f,
  File "/home/user/miniconda3/envs/openpivtkgui/lib/python3.8/tkinter/__init__.py", line 2645, in __init__
    Widget.__init__(self, master, 'button', cnf, kw)
  File "/home/user/miniconda3/envs/openpivtkgui/lib/python3.8/tkinter/__init__.py", line 2567, in __init__
    self.tk.call(
_tkinter.TclError: unknown color name "None"
```

**Comment by ErichZimmer** [comment]
@alexlib ,
I'll check it out, but I have to go to bed soon :(

**Comment by ErichZimmer** [comment]
It appears to be caused by the color picker  in `__init_vel_colorpicker`, but I have no idea what went wrong as I just re-evaluated PIV Challenge 2001 with a clone from the upstream repository. I also downloaded the repository as a zip directly from GitHub, and both worked as intended. Maybe, this is a LINUX issues? There were past compatibility issues on different platforms that had to be resolved, so maybe this could be a new one? I don't have a LINUX or Mac computer at hand, so I would not be able to provide much assistance. :(

**Comment by ErichZimmer** [comment]
By looking at your error, try deleting the .json file as it appears to be caused by an option in the color bar that doesn't exist?? (sorry for spam, I'm very tired after a long day)

Edit:
Deleting the .json file should fix the issue as the colormap `None` was renamed to `viridis`. I had a similar issue and that resolved it. "When in doubt, delete the .json file" :P

**Comment by eguvep** [comment]
I just tested version 0.4.1 on my Ubuntu 18.04 machine and everything went well – with an existing .json settings file.

**Comment by ErichZimmer** [comment]
@alexlib and @eguvep ,
Please test the postprocessing algorithm `local median validation`. I kept getting errors and it worries me.

**Comment by eguvep** [comment]
Yes, I get the same error »filter footprint array has incorrect shape« https://github.com/scipy/scipy/blob/f2ec91c4908f9d67b5445fbfacce7f47518b35d1/scipy/ndimage/filters.py#L965

**Comment by eguvep** [comment]
I am not sure, is something wrong with this line https://github.com/OpenPIV/openpiv-python/blob/ab2144cb2bd0fcd9fce2deeec8cdae3700168b0b/openpiv/validation.py#L247 @alexlib?

**Pull request merged**
